# Generated by Django 6.0.3 on 2026-04-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("doctor", "Doctor"),
                    ("receptionist", "Receptionist"),
                    ("admin", "Admin"),
                ],
                default="patient",
                max_length=20,
            ),
        ),
    ]
