# Generated by Django 6.0.3 on 2026-04-07 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_doctorprofile_patientprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="DoctorProfile",
        ),
        migrations.DeleteModel(
            name="PatientProfile",
        ),
    ]
